package com.geeksforless.tdd_web.type;

public enum FunctionOperation {

    CALCULATE, CALCULATE_POINTS_IN_SEGMENT_BY_STEP, CREATE_POINTS_IN_GIVEN_SEGMENT_WITH_GIVEN_STEP,
    GET_MAX_VALUE, GET_MIN_VALUE, GET_TOTAL_VALUE, GET_AVERAGE_VALUE, FIND_MAX_POINT_WITH_INDEX,
    FIND_MIN_POINT_WITH_INDEX
}
